// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux not configured for Firebase.',
        );
      default:
        throw UnsupportedError(
          'Unsupported platform.',
        );
    }
  }

  // ---------------- WEB ----------------

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC2PAHRs0xw0wZd43wnm3no0rj4kA_Scg',
    appId: '1:576360354973:web:2b53f012cc90d16c5ef074',
    messagingSenderId: '576360354973',
    projectId: 'simul-deskweb-app',
    authDomain: 'simul-deskweb-app.firebaseapp.com',
    storageBucket: 'simul-deskweb-app.firebasestorage.app',
  );
  // ---------------- ANDROID ----------------

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZA_sOrslRRvKjFB7XcFKMn03VPlT3w4',
    appId: '1:576360354973:android:26bc781e2659231c5ef074',
    messagingSenderId: '576360354973',
    projectId: 'simul-deskweb-app',
    storageBucket: 'simul-deskweb-app.firebasestorage.app',
  );
  // ---------------- iOS ----------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIkRPIeedz_8IpKG3wsLPadPjQ74nDpIE',
    appId: '1:964548523301:ios:10c27550f7cbd1454cd6cc',
    messagingSenderId: '964548523301',
    projectId: 'arsneha-c30fd',
    storageBucket: 'arsneha-c30fd.firebasestorage.app',
    iosBundleId: 'com.simul.app',
  );

  // ---------------- macOS ----------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIkRPIeedz_8IpKG3wsLPadPjQ74nDpIE',
    appId: '1:964548523301:ios:10c27550f7cbd1454cd6cc',
    messagingSenderId: '964548523301',
    projectId: 'arsneha-c30fd',
    storageBucket: 'arsneha-c30fd.firebasestorage.app',
    iosBundleId: 'com.simul.app',
  );

  // ---------------- WINDOWS ----------------

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC2PAHRs0xw0wZd43wnm3no0rj4kA_Scg',
    appId: '1:576360354973:web:f8397af80dc7dce85ef074',
    messagingSenderId: '576360354973',
    projectId: 'simul-deskweb-app',
    authDomain: 'simul-deskweb-app.firebaseapp.com',
    storageBucket: 'simul-deskweb-app.firebasestorage.app',
  );
}
